import type { FinalResultEvent, FinalStanding, Medal } from "../types";

export const MEDAL_LABELS: Record<Medal, string> = {
  gold: "Gold",
  silver: "Silver",
  bronze: "Bronze",
};

export const MEDAL_COLORS: Record<Medal, string> = {
  gold: "#B8860B",
  silver: "#6B7280",
  bronze: "#B3541E",
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function csvCell(value: string | number): string {
  const text = String(value);
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function buildResultSheetHtml(result: FinalResultEvent): string {
  const rows = result.standings
    .map((standing) => {
      const medal = standing.medal
        ? `<span style="font-weight:700;color:${MEDAL_COLORS[standing.medal]}">${MEDAL_LABELS[standing.medal]}</span>`
        : "";
      return `<tr>
        <td style="border:1px solid #d9dee5;padding:8px;text-align:center">${standing.position}</td>
        <td style="border:1px solid #d9dee5;padding:8px;text-align:center">${standing.bibNumber}</td>
        <td style="border:1px solid #d9dee5;padding:8px">${escapeHtml(standing.athlete)}</td>
        <td style="border:1px solid #d9dee5;padding:8px">${escapeHtml(standing.club)}</td>
        <td style="border:1px solid #d9dee5;padding:8px;text-align:center">${escapeHtml(standing.result)}</td>
        <td style="border:1px solid #d9dee5;padding:8px;text-align:center">${medal}</td>
      </tr>`;
    })
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(result.eventName)} — Final Results</title>
  <style>
    body { font-family: Arial, Helvetica, sans-serif; color: #1d1d1f; margin: 32px; }
    h1 { font-size: 18px; margin: 0 0 4px; }
    .meta { font-size: 12px; color: #555b63; margin-bottom: 20px; }
    .winner { font-size: 12px; font-weight: 700; color: #0140a7; margin-bottom: 16px; }
    table { border-collapse: collapse; width: 100%; }
    th { border: 1px solid #d9dee5; padding: 8px; background: #f7f8fa; font-size: 11px; text-align: center; }
    td { font-size: 12px; }
    .stamp { margin-top: 24px; font-size: 10px; color: #8b9098; }
  </style>
</head>
<body>
  <h1>${escapeHtml(result.eventName)}</h1>
  <div class="meta">${escapeHtml(result.eventDate)} · ${escapeHtml(result.venue)}</div>
  <div class="winner">Winner: ${escapeHtml(result.winner)}</div>
  <table>
    <thead>
      <tr><th>Pos</th><th>Bib</th><th>Athlete</th><th>Club</th><th>Result</th><th>Medal</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="stamp">Generated by EACRMS — Ethiopian Athletics Federation · ${new Date().toLocaleString()}</div>
</body>
</html>`;
}

function openPrintWindow(html: string): void {
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.focus();
  window.setTimeout(() => win.print(), 350);
}

export function exportResultsAsPdf(result: FinalResultEvent): void {
  openPrintWindow(buildResultSheetHtml(result));
}

export function printResults(result: FinalResultEvent): void {
  openPrintWindow(buildResultSheetHtml(result));
}

export function exportResultsAsExcel(result: FinalResultEvent): void {
  const header = ["Position", "Bib", "Athlete", "Club", "Result", "Medal"];
  const rows = result.standings.map((standing: FinalStanding) =>
    [
      standing.position,
      standing.bibNumber,
      standing.athlete,
      standing.club,
      standing.result,
      standing.medal ? MEDAL_LABELS[standing.medal] : "",
    ]
      .map(csvCell)
      .join(",")
  );
  const csv = `\uFEFF${[header.map(csvCell).join(","), ...rows].join("\r\n")}`;
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `final-results-${result.id}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
